exports.testCompany = {
  name: 'The Test Company',
  csin: '1Q2W3E4R5T',
  canalystTicker: 'TEST_US',
  bloombergTicker: 'TEST US',
  countryCode: 'us',
  version: 'Q3-2023.25',
  mostRecentPeriod: 'Q3-2023',
  mrpDuration: 'fiscal_quarter',
  mrpStartDate: '2023-04-01',
  mrpEndDate: '2023-06-30',
  isInCoverage: true,
  reportingFrequency: 'QFY',
  tradingCurrency: 'USD',
  reportingCurrency: 'USD',
}